In [39]:
import numpy as np
arr=np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [40]:
arr=np.array([1,2,3,4],dtype="uint8")
arr.dtype

dtype('uint8')

In [41]:
arr

array([1, 2, 3, 4], dtype=uint8)

In [42]:
arr[3]

4

In [43]:
arr1=arr[0:2]
arr1

array([1, 2], dtype=uint8)

In [44]:
arr2=arr[0:2].copy()
arr2[0]=40

In [45]:
arr[0]=30
arr1
arr

array([30,  2,  3,  4], dtype=uint8)

In [46]:
arr2

array([40,  2], dtype=uint8)